service: v1-service-commit-cron

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2
  lambdaHashingVersion: 20201221
  # timeout: 20
  environment:
    REDIS_HOST: ${env:REDIS_HOST}
  vpc:
    securityGroupIds:
      - sg-03ffad66ac15ffd3b
    subnetIds:
      - subnet-04d5280121178b2b0

functions:
  lambda_handler:
    handler: handler.lambda_handler
    events:
      - schedule: cron(0 3 1/1 * ? *)
    #  - httpApi:
    #      path: /users/create
    #      method: get
    #  - s3: ${env:BUCKET}

plugins:
  - serverless-python-requirements
  # - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true