service: v1-service-commit-cron

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221

functions:
  lambda_handler:
    handler: handler.lambda_handler
   events:
    #  - httpApi:
    #      path: /users/create
    #      method: get
    #  - s3: ${env:BUCKET}
     - schedule: cron(0 3 1/1 * ? *)
